name: Survival
version: '${project.version}'
main: cz.florixak.survival.Survival
api-version: 1.19
authors: [ FloriXak ]
softdepend: [ Vault, LuckPerms, PlaceholderAPI, HpsCore ]

commands:
  survival:
  clear:
  gamemode:
  gm:
  game:
  heal:
  doctor:
  home:
  sethome:
  delhome:
  homes:
  anvil:
  anv:
  wb:
  workbench:
  ct:
  craftingtable:
  ec:
  enderchest:
  echest:
  jobs:
  prace:
  job:
  kit:
  kits:
  money:
  coins:
  cash:
  balance:
  bank:
  arena:
  pvparena:
  shop:
  obchod:
  store:
  market:
  spawn:
  setspawn:
  delspawn:
  warp:
  warps:
  setwarp:
  delwarp:
  coord:
  coords:
  coordinates:
  fly:
  help:
  pomoc:
  rtp:
  randomtp:
  randomteleport:
  rteleport:
  ruleta:
  roulette:
  stats:
  statistics:
  tp:
  teleport:
  tpa:
  tpaccept:
  tpdeny:
  tpblock:
  back:
  pay:
  zaplatit: